"""Initial migration

Revision ID: bf173c6d0cec
Revises: 
Create Date: 2019-11-13 16:26:30.474080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf173c6d0cec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(length=2047), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.Unicode(length=2047), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.Unicode(length=255), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technical_contact_id', sa.Integer(), nullable=False),
    sa.Column('primary_contact_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Unicode(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['primary_contact_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['technical_contact_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'technical_contact_id', 'primary_contact_id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('group_to_role',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'role_id')
    )
    op.create_table('user_to_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('sitemap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Unicode(length=1023), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('last_confirmed_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id', 'owner_id')
    )
    op.create_table('namespace',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.Unicode(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('sitemap_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['sitemap_id'], ['sitemap.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('namespace')
    op.drop_table('sitemap')
    op.drop_table('user_to_group')
    op.drop_table('group_to_role')
    op.drop_table('agent')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('group')
    # ### end Alembic commands ###
